### ISSUE TITLE
Locked to Node v8

### ISSUE THREAD

**Issue by DaKaZ** [schibsted/node-token-introspection#16]
Hello,

I am using your model to handle token introspection for us, and technically your module is locked to node v8.  Is there any reason why or can we submit a PR to bring the to v10 as well?

**Comment by joawan** [comment]
Hi,

No reason really, just an oversight I think.
I PRd a fix for it, including update to dependencies.

**Comment by joawan** [comment]
Version 1.2.0 just published. Let me know if you need anything else
https://www.npmjs.com/package/token-introspection/v/1.2.0

**Comment by DaKaZ** [comment]
Really appreciate it!
