### ISSUE TITLE
Cache token

### ISSUE THREAD

**Issue by brunobritodev** [schibsted/node-token-introspection#18]
IdentityServer4 use a component called IdentityModel that has a class [IdentityModel.AspNetCore.OAuth2Introspection](https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/blob/master/src/OAuth2IntrospectionHandler.cs).

Like you guys, first the component check JWT locally, after that check it at OAuth2 Instrospection Endpoint, then cache the token for 5 minutes (Default). Why? to prevent massive calls and temporary problems with Auth Server.

In your opinion something like that is a good feature request?

**Comment by joawan** [comment]
Hello,

Thank you for your suggestion!

We've intentionally kept caching strategy out of this implementation, same with express middleware and similar. I had thoughts on providing a middleware with cache, but it quickly gets too opinionated.

This is a middleware we currently use: https://gist.github.com/joawan/f1cefbb8ee5b8fc90503ce32f21181a8

We run the token introspection in 2 different ways, one as that middleware and the other as authorizer lambda, with the serverless framework. For the latter, AWS will cache the response from the authorizer for a set period of time, avoiding the lambda invocation completely.

Given that caching can get opinionated, and we have use cases were cache is unnecessary, I don't think adding a cache to this lib is a good idea.

**Comment by brunobritodev** [comment]
Hi @joawan,

Thx for extra explanation and use cases. It helped me a lot!!

swt thx
