### ISSUE TITLE
TLS connection

### ISSUE THREAD

**Issue by FrancoisXavierNoe** [schibsted/node-token-introspection#22]
Hello,

Can you explain me how we can manage a TLS connection with node-token-introspection ?

Thank you,

**Comment by joawan** [comment]
Hello,

Can you elaborate a bit? How would you like to manage a TLS connection?

**Comment by FrancoisXavierNoe** [comment]
Currently, when I try to intropesct a token, I have an error :
Remote token introspection request failed: request to https://xxxxxx.com/oauth-server/introspect failed, reason: self signed certificate in certificate chain

I think It is because I use an https protocol, but the TLS configuration is not done.
I don't understand where I can configure the secure connection (with certificate and key)

In the index.js, I see that we can use an https-proxy-agent, but I don't want to pass by a proxy, I just want to have a secure connection between my auth server and my application (an https agent with certificate options).

So for example, instead of
      const HttpsProxy = require('https-proxy-agent');
      proxy = new HttpsProxy(options.proxy);
have 
      const Https = require('https');
      proxy = new Https.Agent(options.https);

Is it clearer ?

**Comment by joawan** [comment]
Right, what you are asking for is "how to make insecure connections to your server?".

It's not something I would recommend, and you could just use a letsencrypt certificate.

But, given your question I started digging into it.
It is possible to provide your own instance of node-fetch, or node-fetch compatible package.
https://github.com/schibsted/node-token-introspection/blob/master/src/index.js#L16

The node-fetch constructor in turn accepts an instance of https.agent.
https://www.npmjs.com/package/node-fetch#custom-agent

That custom https agent can be configured to allow insecure connections.
https://nodejs.org/api/https.html#https_https_request_options_callback
See `rejectUnauthorized`

**Comment by FrancoisXavierNoe** [comment]
Thank you for this answer Joawan,

Just to clarify, I **don't want** to make insecure connections. I want to **secure it** !

But I didn't find how to configure a secure connection between my OAuth server and my application  that uses node-token-introspection.

I will look and try this solution of a custom fetch instance, with a custom https agent that can be configured to allow **secure** connections (with crt and key).

**Comment by joawan** [comment]
Ok, you are trying to make a connection to a server using a self-signed certificate.
I guess you can hook into the https.agent to provide client certificate authentication too.

**Comment by FrancoisXavierNoe** [comment]
It's not a self-signed certificate. It is a real certificate.
By the way, I look quickly in the code, and in remote-introspection.js, we have:
```
res = await options.fetch(
        options.endpoint,
        { body: formEncode(data), ...fetchOption },
      );
```
You can see that this package use directly fetchOption when using fetch

And in the fetchOption, we have :
`    agent: options.proxy,`
So, the only agent configurable is a proxy.

I can't have a simple https agent with : 
`agent: new https.Agent(options)`
with 
```
const options = {
    // when using this code in production, for high throughput you should not read
    //   from the filesystem for every call, it can be quite expensive. Instead
    //   consider storing these in memory
    cert: fs.readFileSync(
      path.resolve(__dirname, './path/to/public-cert.pem'),
      `utf-8`,
    ),
    key: fs.readFileSync(
      path.resolve(__dirname, './path/to/private-key.key'),
      'utf-8',
    ),
    passphrase:
      '<your-passphrase>',
    keepAlive: false, // switch to true if you're making a lot of calls from this client
  };
```

**Comment by joawan** [comment]
The error message you provided was
```Remote token introspection request failed: request to https://xxxxxx.com/oauth-server/introspect failed, reason: self signed certificate in certificate chain```

As you can provide your own fetch implementation, you can override that agent.

```js
const myFetch = (endpoint, data) => {
  data.agent = new https.Agent(...);
  return fetch(endpoint, data);
}

tokenIntrospection({..., fetch: myFetch})
```

**Comment by FrancoisXavierNoe** [comment]
It works ! Thank you !

**Comment by joawan** [comment]
👍 Glad I could help!

**Comment by joawan** [comment]
I added this to the readme, in case others have similar questions
https://github.com/schibsted/node-token-introspection#flexibility-in-fetch
